services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - wapikit-dev
    environment:
      - POSTGRES_PASSWORD=wapikit-dev
      - POSTGRES_USER=wapikit-dev
      - POSTGRES_DB=wapikit-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: wapikit-dev-db
        target: /var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - wapikit-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: wapikit-dev-redis
        target: /data

  frontend:
    build:
      context: ../
      dockerfile: dev/dev.Dockerfile
    command: make dev-frontend
    ports:
      - "3000:3000"
    environment:
      - WAPIKIT_API_URL=http://backend:8000
    depends_on:
      - database
      - redis
    volumes:
      - ../:/app
    networks:
      - wapikit-dev

  backend:
    build:
      context: ../
      dockerfile: dev/dev.Dockerfile
    # We'll run the database migrations and then start the backend in dev mode
    command: sh -c "./wapikit --install --idempotent --yes --config dev/config.toml && make dev-backend-docker"
    ports:
      - "8000:8000"
      - "8081:8081"
    depends_on:
      - database
      - redis
    volumes:
      - ../:/app
      - go-modules:/go/pkg/mod
    networks:
      - wapikit-dev

volumes:
  wapikit-dev-db:
  wapikit-dev-redis:
  go-modules:


networks:
  wapikit-dev:
